language: ruby

rvm:
- 1.9.3
- 2.0.0
- 2.1.2

script: bundle exec rspec spec --tag '~integration'

bundler_args: --without development --retry=3 --jobs=3

cache: bundler

sudo: false

deploy:
  provider: rubygems
  api_key:
    secure: FolEBkQI4oiqjZMzuZ/ELSJFxwCrUTmVhew+tr8yrDONOgphjvbOkDFMdPKnM48nMBekz0lS/yh6Ib5JXe0gxk6+fUq/37eNVF7eFc9poTJhJ2I6zkYOunxSTDInLy/Hxl90RXjKNnL+PFNPPZjLSXrUWeUxLViI00Dkfa9iT6s=
  gem: aws_security_viz
  on:
    tags: true
    repo: anaynayak/aws-security-viz
