language: ruby

rvm:
- 2.4.4
- 2.3.4
- 2.2.7
- 2.5.1

script: bundle exec rspec spec --tag '~integration'

before_install: gem install bundler

cache: bundler

sudo: false

deploy:
  provider: rubygems
  api_key:
    secure: FolEBkQI4oiqjZMzuZ/ELSJFxwCrUTmVhew+tr8yrDONOgphjvbOkDFMdPKnM48nMBekz0lS/yh6Ib5JXe0gxk6+fUq/37eNVF7eFc9poTJhJ2I6zkYOunxSTDInLy/Hxl90RXjKNnL+PFNPPZjLSXrUWeUxLViI00Dkfa9iT6s=
  gem: aws_security_viz
  on:
    repo: anaynayak/aws-security-viz
